GET http://localhost:8080/contrats
Content-Type: application/json

###
POST http://localhost:8080/contrats
Content-Type: application/json

< dtos/contrat-4.json

###
GET http://localhost:8080/contrats/N1001
Content-Type: application/json

###
PUT http://localhost:8080/contrats
Content-Type: application/json

< contrat-updated.json

###
DELETE http://localhost:8080/contrats/N1000
Content-Type: application/json